# Generated by Django 2.0.1 on 2018-01-15 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFailureState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('expected_value', models.CharField(max_length=256)),
                ('actual_value', models.CharField(max_length=256)),
                ('test_failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TestFailure')),
            ],
        ),
    ]
