# Generated by Django 2.0.1 on 2018-01-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testsuccess_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
