# Generated by Django 2.0.1 on 2018-01-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180116_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfailure',
            name='arguments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
