# Generated by Django 2.0.1 on 2018-01-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_testfailure_arguments'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfailure',
            name='pretty',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
