# Generated by Django 2.0.1 on 2018-01-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testsignalerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='opcode',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
