# Generated by Django 2.0.1 on 2018-01-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180118_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFailureInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=256)),
                ('test_failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TestFailure')),
            ],
        ),
        migrations.CreateModel(
            name='TestSignalErrorInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=256)),
                ('test_signal_error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TestSignalError')),
            ],
        ),
    ]
