# Generated by Django 2.0.7 on 2018-07-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_testfailureinput_testsignalerrorinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfailure',
            name='bytes',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='testsignalerror',
            name='bytes',
            field=models.CharField(default='', max_length=256),
        ),
    ]
