# Generated by Django 2.0.7 on 2018-07-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180727_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuccess',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='testsuccess',
            name='opcode',
        ),
        migrations.DeleteModel(
            name='TestSuccess',
        ),
    ]
