# Generated by Django 2.0.7 on 2018-07-30 18:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('main', '0013_auto_20180730_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestFailure',
            new_name='TestResult',
        ),
        migrations.RenameModel(
            old_name='TestFailureInput',
            new_name='TestResultInput',
        ),
        migrations.RenameModel(
            old_name='TestFailureState',
            new_name='TestResultState',
        ),
    ]
