# Generated by Django 2.0.7 on 2018-07-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180730_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsignalerrorinput',
            name='test_signal_error',
        ),
        migrations.DeleteModel(
            name='TestSignalErrorInput',
        ),
    ]
