# Generated by Django 2.0.7 on 2018-07-30 18:10

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('main', '0015_auto_20180730_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestResult',
            new_name='Test',
        ),
        migrations.RenameModel(
            old_name='TestResultInput',
            new_name='TestInput',
        ),
        migrations.RenameModel(
            old_name='TestResultState',
            new_name='TestState',
        ),
    ]
