# Generated by Django 2.0.7 on 2018-07-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180730_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsignalerror',
            name='signal',
        ),
        migrations.AddField(
            model_name='test',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='signal',
            field=models.IntegerField(null=True),
        ),
    ]
