# Generated by Django 2.0.7 on 2018-07-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180730_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestState',
            new_name='TestMachineState',
        ),
    ]
